# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F58zkTAxV7fM4S7hE4sTq80Hbua8c35U
"""

numero1 = int(input("Inserte el numero 1: "))

numero2 = int(input("Inserte el numero 2: "))

def sum (numero1, numero2):
  result =numero1 + numero2
  print(numero1, "+", numero2, "=", result)

def sub (numero1, numero2):
  result =numero1 - numero2
  print(numero1, "-", numero2, "=", result)

def mul(numero1, numero2):
  result = numero1 * numero2
  print(numero1, "*", numero2, "=", result)

def div(numero1, numero2):
  if (numero2 != 0):
    result = numero1 / numero2
    print(numero1, "/", numero2, "=", result)
  else:
    print("El numero es cero no se puede dividir")

sum(numero1, numero2)
sub(numero1, numero2)
mul(numero1, numero2)
div(numero1, numero2)