# -*- coding: utf-8 -*-
"""Juego Adivinanza

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLQF_BV4tlde8GW24HvoJ827EsWk00yj
"""

import random
def juego_adivinanzas():
  numero_secreto = random.randint(1, 100)
  intentos = 0
  adivinando = False

  print("Bienvenido al juego de adivinanzas de numeros!")
  print("Estoy pensando en un numero entre el 1 y el 100")

  while True:
    intento = int(input("Adivina el número: "))
    intentos += 1
    if intento > numero_secreto:
      print(f"El numero secreto en menor.")
import random
def juego_adivinanzas():
  numero_secreto = random.randint(1, 100)
  intentos = 0
  adivinando = False

  print("Bienvenido al juego de adivinanzas de numeros!")
  print("Estoy pensando en un numero entre el 1 y el 100")

  while True:
    intento = int(input("Adivina el número: "))
    intentos += 1
    if intento > numero_secreto:
      print(f"El numero secreto en menor.")
    elif intento < numero_secreto:
      print(f"El numero secreto es mayor.")
    else:

      print(f"¡Felicidades! Adivinaste el número {numero_secreto} en {intentos} intentos.")
      break

juego_adivinanzas()

import random
def juego_adivinanzas():
  numero_secreto = random.randint(1, 100)
  intentos = 0
  adivinando = False

  print("Bienvenido al juego de adivinanzas de numeros!")
  print("Estoy pensando en un numero entre el 1 y el 100")

  while True:
    intento = int(input("Adivina el número: "))
    intentos += 1
    if intento > numero_secreto:
      print(f"El numero secreto en menor.")
import random
def juego_adivinanzas():
  numero_secreto = random.randint(1, 100)
  intentos = 0
  adivinando = False

  print("Bienvenido al juego de adivinanzas de numeros!")
  print("Estoy pensando en un numero entre el 1 y el 100")

  while True:
    intento = int(input("Adivina el número: "))
    intentos += 1
    if intento > numero_secreto:
      print(f"El numero secreto en menor.")
    elif intento < numero_secreto:
      print(f"El numero secreto es mayor.")
    else:

      print(f"¡Felicidades! Adivinaste el número {numero_secreto} en {intentos} intentos.")
      break

juego_adivinanzas()