# -*- coding: utf-8 -*-
"""Tienda de Zapatos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NE3FKtJ5jKCfJO4mzl63kabZRyjuADSX

Eres el gerente de una tienda de zapatos y necesitas controlar tu inventario.

Cada vez que vendes un par de zapatos, disminuyes tu inventario. Quieres tener un programa que te permita ingresar la cantidad inicial de pares de zapatos en tu tienda y luego, sucesivamente, te pregunte cuántos pares de zapatos se vendieron. El programa debe continuar preguntando cuántos pares de zapatos se vendieron hasta que el inventario llegue a cero. Finalmente, el programa debe decirte cuántas transacciones (ventas individuales) tuvieron lugar antes de que se acabara el inventario.
"""

# Cantidad inicial de pares de zapatos
inventario = int(input("Ingrese la cantidad inicial de pares de zapatos en la tienda: "))
transacciones = 0
print(f"El inventario contiene {inventario} pares de zapatos.")

while inventario > 0:
    if inventario < 10:
        print("Advertencia: el inventario está casi vacío.")

    num_zapatos = int(input("¿Cuántos pares de zapatos quiere el cliente? "))

    if num_zapatos > inventario:
        print(f"No hay stock para tanta cantidad. Solo hay {inventario} pares disponibles.")
    else:
        inventario -= num_zapatos
        transacciones += 1
        print(f"El cliente ha pedido {num_zapatos} pares. Ahora tienes {inventario} pares en el inventario.")

print(f"Se realizaron un total de {transacciones} transacciones antes de que se acabara el inventario.")